import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_FROM = os.getenv("MAIL_FROM")
MAIL_SERVER = os.getenv("MAIL_SERVER")
MAIL_STARTTLS = os.getenv("MAIL_STARTTLS")
MAIL_SSL_TLS = os.getenv("MAIL_SSL_TLS")
USE_CREDENTIALS = os.getenv("USE_CREDENTIALS")
VALIDATE_CERTS = os.getenv("VALIDATE_CERTS")
MAIL_PORT = os.getenv("MAIL_PORT", 465)
CODE_LINK = os.getenv("CODE_LINK")
CONNECTION_RABBIT=os.getenv("CONNECTION_RABBIT")
TIME_ZONE=os.getenv("TIME_ZONE")
HEARTBEAT_INTERVAL=os.getenv("HEARTBEAT_INTERVAL")
MIN_HEARTBEAT=os.getenv("MIN_HEARTBEAT")