export const dataTransactionPayement = [{
    id: 1,
    Client: "John Doe",
    Montant: "20000 Ar",
    Date: "2025-01-09",
    Heure: "00:00",
    Type: "Recharge",
    Methode:"Carte credit",
    statut: "Complétée",
  },
  {
    id: 2,
    Client: "Jane Smith",
    Montant: "15000 Ar",
    Date: "2025-02-10",
    Heure: "00:00",
    Type: "Reservation",
    Methode:"",
    statut: "En attente",
  },
  {
    id: 3,
    Client: "Alice Brown",
    Montant: "72700 Ar",
    Date: "2025-03-12",
    Heure: "00:00",
    Type: "Recharge",
    Methode:"Paypal",
    statut: "Complétée",
  },
  {
    id: 4,
    Client: "Bob Johnson",
    Montant: "28700 Ar",
    Date: "2025-04-15",
    Heure: "30:00",
    Type: "Recharge",
    Methode:"Mobile money",
    statut: "Complétée",
  },
  {
    id: 5,
    Client: "Charlie Davis",
    Montant: "38800 Ar",
    Date: "2025-05-18",
    Heure: "15:00",
    Type: "Annulation",
    Methode:"Mobile Money",
    statut: "Remboursée",
  },]